import Head from 'next/head';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Button from '../components/Button';
import Heading from '../components/Heading';

export default function Home() {
  return (
    <>
      <Head>
        <title>SnapSell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-100 min-h-screen w-full flex items-center justify-center flex-col">
        <div className="flex flex-col sm:flex-row sm:items-end mx-5  sm:mx-10 absolute z-20 top-[10%]  sm:font-normal text-black text-[2.1rem] sm:text-5xl lg:text-7xl 2xl:text-[5rem]">
          <span className="sm:pb-3">Welcome to</span>
          <div className="flex">
            <img
              src={'/snapsell-black-square.png'}
              alt="Hi Street"
              className="w-12 sm:w-[120px] 2xl:w-[120px]  sm:pr-4 2xl:pr-2 mr-1 sm:ml-9 sm:mr-0"
            />
            <span className=" flex items-center text-5xl sm:text-6xl lg:text-8xl 2xl:text-9xl pb-2 sm:pb-0">
              SnapSell
            </span>
          </div>
        </div>
        <h1 className="text-7xl font-bold text-center">
          Ecommerce, made easy.
        </h1>
        <h2 className="text-4xl mt-2 mb-8">
          Quickly and easily setup your own online store
        </h2>
        <div className="flex items-center justify-center gap-2">
          <Link href={`/auth/sign-in`}>
            <Button size="xl" appearance="primary" type="button">
              Sign In
            </Button>
          </Link>
          <Link href={`/auth/sign-up`}>
            <Button size="xl" appearance="outline" type="button">
              Sign Up
            </Button>
          </Link>
        </div>
      </div>
    </>
  );
}
