import Head from 'next/head';
import Link from 'next/link';
import { Inter } from 'next/font/google';
import Button from '../components/Button';

const inter = Inter({ subsets: ['latin'] });

const menuItems = [
  {
    id: 'Sign Up',
    name: 'Sign Up',
    href: '/sign-up',
  },
  {
    id: 'Sign In',
    name: 'Sign In',
    href: '/sign-in',
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>SnapSell</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-[calc(100vh-0px)] relative overflow-hidden">
        <div className=" flex px-5 sm:px-10 absolute z-20 top-[20%]  sm:font-normal text-white text-3xl sm:text-6xl md:text-7xl lg:text-8xl">
          Welcome to
          <img
            src={'/snapsell-white-square.png'}
            alt="SnapSell"
            className="w-9 sm:w-[120px] sm:pr-2 ml-3 mr-1 sm:ml-9 sm:mr-0"
          />
          SnapSell
        </div>
        <h2 className="px-5 sm:px-10 absolute z-20 top-[30%] sm:top-[35%] sm:text-2xl md:text-3xl lg:text-4xl text-white">
          Probably the finest customizable storefront for your business
        </h2>
        <img
          src={'/GE23cTcUXww-unsplash.jpg'}
          alt={'SnapSell'}
          className="sm:w-[100vw] object-cover h-full"
        />
        <div className="flex gap-4 absolute top-0 h-full w-full z-20 justify-center items-center">
          {menuItems.map((item) => (
            <Link key={item.id} href={`/auth${item.href}`}>
              {item.name === 'Sign Up' && <Button
                key={item.id}
                href={`/auth${item.href}`}
                size="xl"
                appearance="homepage"
                type="button"
                children={item.name}
              ></Button>}
              {item.name === 'Sign In' &&
                <Button
                  key={item.id}
                  href={`/auth${item.href}`}
                  size="xl"
                  appearance="homepageSubtle"
                  type="button"
                  children={item.name}
                ></Button>}
            </Link>
          ))}
        </div>
        <div className="absolute top-0 bg-black bg-opacity-30 h-full w-full z-10"></div>
        <p className="absolute bottom-0 text-white text-xs sm:text-base">
          Photo by Viktor Forgacs on Unsplash
        </p>
      </div>
      {/*<div className="h-[208px] bg-gray-800"></div>*/}
    </>
  );
}
